logging:
  level:
    root: info
    org.springframework.jdbc.core: trace

spring:
  liquibase:
    clear-checksums: false
  application:
    name: telescope
  datasource:
    url: jdbc:postgresql://localhost:5433/telescope
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    properties.hibernate:
      show_sql: true
      format_sql: true
      hbm2ddl:
        auto: update
      default_batch_fetch_size: 50
    open-in-view: false
  servlet.multipart:
    enabled: true
    max-file-size: 10MB
    max-request-size: 10MB
app:
  security:
    secret: 5JzoMbk6E5qIqHSuBTgeQCARtUsxAkBiHwdjXOSW8kWdXzYmP3X51C0


